image:  
  repository: bitnamilegacy/drupal
  tag: 11.2.3-debian-12-r2

drupalUsername: admin
drupalPassword: superPass123!

externalDatabase:
  host: mariadb.dev.svc.cluster.local
  port: 3306
  database: drupal
  user: drupal
  existingSecret: "drupal-db-conn"

mariadb:
  enabled: false

service:
  type: ClusterIP
