image:  
  repository: bitnamilegacy/drupal
  tag: 11.2.3-debian-12-r2

drupalUsername: admin

externalDatabase:
  host: mariadb.drupal-app.svc.cluster.local
  port: 3306
  database: drupal
  user: drupal
  existingSecret: "drupal-db-conn"

mariadb:
  enabled: false

service:
  type: ClusterIP
  loadBalancerIP: "172.18.250.1"